import {
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  CircleStackIcon,
  CogIcon,
  RectangleGroupIcon,
  RocketLaunchIcon,
  SparklesIcon,
  SquaresPlusIcon,
} from "@heroicons/react/24/outline";

export const CustomerData = [
  {
    id: 1,
    name: "Alice",
    language: "English",
    content_type: "Redirect",
    version: 123,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 01,2022 10:45",
    tags: "TagA, TagB",
    modified_name: "Bob",
  },
  {
    id: 2,
    name: "Bob",
    language: "Spanish",
    content_type: "Blog Content",
    version: 456,
    publish_stage: "Review",
    workflow_stages: "Completed",
    modified_at: "Jun 02,2022 12:30",
    tags: "TagC, TagD",
    modified_name: "Charlie",
  },
  {
    id: 3,
    name: "Charlie",
    language: "French",
    content_type: "Podcasts",
    version: 789,
    publish_stage: "Published",
    workflow_stages: "Overdue",
    modified_at: "Jun 03,2022 15:20",
    tags: "TagE, TagF",
    modified_name: "David",
  },
  {
    id: 4,
    name: "David",
    language: "German",
    content_type: "Social Media",
    version: 101,
    publish_stage: "Archived",
    workflow_stages: "Draft",
    modified_at: "Jun 04,2022 08:10",
    tags: "TagG, TagH",
    modified_name: "Eva",
  },
  {
    id: 5,
    name: "Eva",
    language: "Italian",
    content_type: "Videos",
    version: 202,
    publish_stage: "Scheduled",
    workflow_stages: "In Progress",
    modified_at: "Jun 05,2022 14:15",
    tags: "TagI, TagJ",
    modified_name: "Frank",
  },
  {
    id: 6,
    name: "Frank",
    language: "Portuguese",
    content_type: "Redirector",
    version: 303,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 06,2022 11:55",
    tags: "TagK, TagL",
    modified_name: "Grace",
  },
  {
    id: 7,
    name: "Grace",
    language: "Russian",
    content_type: "Redirect",
    version: 404,
    publish_stage: "Review",
    workflow_stages: "Completed",
    modified_at: "Jun 07,2022 09:25",
    tags: "TagM, TagN",
    modified_name: "Henry",
  },
  {
    id: 8,
    name: "Henry",
    language: "Spanish",
    content_type: "Redirect",
    version: 505,
    publish_stage: "Published",
    workflow_stages: "Overdue",
    modified_at: "Jun 08,2022 13:40",
    tags: "TagO, TagP",
    modified_name: "Isabel",
  },
  {
    id: 9,
    name: "Isabel",
    language: "French",
    content_type: "Redirect",
    version: 606,
    publish_stage: "Archived",
    workflow_stages: "Draft",
    modified_at: "Jun 09,2022 16:50",
    tags: "TagQ, TagR",
    modified_name: "Jack",
  },
  {
    id: 10,
    name: "Jack",
    language: "English",
    content_type: "Political Media",
    version: 707,
    publish_stage: "Scheduled",
    workflow_stages: "In Progress",
    modified_at: "Jun 10,2022 10:15",
    tags: "TagS, TagT",
    modified_name: "Karen",
  },
  {
    id: 11,
    name: "Karen",
    language: "German",
    content_type: "Social Media",
    version: 808,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 11,2022 12:05",
    tags: "TagU, TagV",
    modified_name: "Larry",
  },
  {
    id: 12,
    name: "Larry",
    language: "Italian",
    content_type: "Social Media",
    version: 909,
    publish_stage: "Review",
    workflow_stages: "Completed",
    modified_at: "Jun 12,2022 14:30",
    tags: "TagW, TagX",
    modified_name: "Mia",
  },
  {
    id: 13,
    name: "Mia",
    language: "Spanish",
    content_type: "Social Media",
    version: 1010,
    publish_stage: "Published",
    workflow_stages: "Overdue",
    modified_at: "Jun 13,2022 16:20",
    tags: "TagY, TagZ",
    modified_name: "Nick",
  },
  {
    id: 14,
    name: "Nick",
    language: "French",
    content_type: "Social Media",
    version: 1111,
    publish_stage: "Archived",
    workflow_stages: "Draft",
    modified_at: "Jun 14,2022 08:45",
    tags: "Tag1, Tag2",
    modified_name: "Olivia",
  },
  {
    id: 15,
    name: "Olivia",
    language: "Portuguese",
    content_type: "Social Media",
    version: 1212,
    publish_stage: "Scheduled",
    workflow_stages: "In Progress",
    modified_at: "Jun 15,2022 14:15",
    tags: "Tag3, Tag4",
    modified_name: "Paul",
  },
  {
    id: 16,
    name: "Paul",
    language: "Russian",
    content_type: "Social Media",
    version: 1313,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 16,2022 11:55",
    tags: "Tag5, Tag6",
    modified_name: "Quinn",
  },
  {
    id: 17,
    name: "Rachel",
    language: "English",
    content_type: "Blog Content",
    version: 1414,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 17,2022 10:45",
    tags: "Tag7, Tag8",
    modified_name: "Sam",
  },
  {
    id: 18,
    name: "Sam",
    language: "Spanish",
    content_type: "Podcasts",
    version: 1515,
    publish_stage: "Review",
    workflow_stages: "Completed",
    modified_at: "Jun 18,2022 12:30",
    tags: "Tag9, Tag10",
    modified_name: "Tina",
  },
  {
    id: 19,
    name: "Tina",
    language: "French",
    content_type: "Redirector",
    version: 1616,
    publish_stage: "Published",
    workflow_stages: "Overdue",
    modified_at: "Jun 19,2022 15:20",
    tags: "Tag11, Tag12",
    modified_name: "Ulysses",
  },
  {
    id: 20,
    name: "Ulysses",
    language: "German",
    content_type: "Videos",
    version: 1717,
    publish_stage: "Archived",
    workflow_stages: "Draft",
    modified_at: "Jun 20,2022 08:10",
    tags: "Tag13, Tag14",
    modified_name: "Victoria",
  },
  {
    id: 21,
    name: "Victoria",
    language: "Italian",
    content_type: "Redirector",
    version: 1818,
    publish_stage: "Scheduled",
    workflow_stages: "In Progress",
    modified_at: "Jun 21,2022 14:15",
    tags: "Tag15, Tag16",
    modified_name: "Walter",
  },
  {
    id: 22,
    name: "Walter",
    language: "Portuguese",
    content_type: "Social Media",
    version: 1919,
    publish_stage: "Draft",
    workflow_stages: "In Progress",
    modified_at: "Jun 22,2022 11:55",
    tags: "Tag17, Tag18",
    modified_name: "Xena",
  },
  {
    id: 23,
    name: "Xena",
    language: "Russian",
    content_type: "Blog Content",
    version: 2020,
    publish_stage: "Review",
    workflow_stages: "Completed",
    modified_at: "Jun 23,2022 09:25",
    tags: "Tag19, Tag20",
    modified_name: "Yohan",
  },
  {
    id: 24,
    name: "Yohan",
    language: "Spanish",
    content_type: "Social Media",
    version: 2121,
    publish_stage: "Published",
    workflow_stages: "Overdue",
    modified_at: "Jun 24,2022 13:40",
    tags: "Tag21, Tag22",
    modified_name: "Zara",
  },
  {
    id: 25,
    name: "Zara",
    language: "French",
    content_type: "Videos",
    version: 2222,
    publish_stage: "Archived",
    workflow_stages: "Draft",
    modified_at: "Jun 25,2022 16:50",
    tags: "Tag23, Tag24",
    modified_name: "Andy",
  },
];

export const tabs = {
  DASHBOARD: "Dashboard",
  ENTRIES: "Entries",
  ASSETS: "Assets",
  CONTENT_MODELS: "Content Models",
  PUBLISH_QUEUE: "Publish Queue",
  RELEASES: "Releases",
  TASKS: "Tasks",
  SETTINGS: "Settings",
};

export const tabsIcons = {
  Dashboard: <SquaresPlusIcon />,
  Entries: <RectangleGroupIcon />,
  Assets: <SparklesIcon />,
  "Content Models": <CircleStackIcon />,
  "Publish Queue": <RocketLaunchIcon />,
  Releases: <CogIcon />,
  Tasks: <ArchiveBoxIcon />,
  Settings: <AdjustmentsHorizontalIcon />,
};
